
# TODO!!! need to run the migrations for the DB before the sk-api can run. 
# put an intermediate migrations container to run these between postgres & sk?

networks:
    tapis:
        name: tapis
        external: true


services:
    systems-api:
        image: {{ systems_api_image }}
        networks:
            - tapis

    systems-postgres:
        image: {{ systems_postgres_image }}
        networks:
            - tapis
