---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications-postgres
  name: notifications-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notifications-postgres
    spec:
      containers:
      - name: notifications-postgres
        image: postgres:11
        ports:
          - containerPort: 5432
        env:
        - name: PGDATA
          value: "/pgdata/data"
        - name: TOKENS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-config
              key: service_tenant_base_url
        - name: TENANTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-config
              key: service_tenant_base_url
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-notifications-secrets
              key: postgres-password
        envFrom:
        - configMapRef:
            name: notifications-environment-vars
        volumeMounts:
        - mountPath: /pgdata
          name: pgdata
          subPath: postgres
      hostname: notifications-postgres
      restartPolicy: Always
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: notifications-pgdata
