---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications-rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: notifications-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: notifications-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notifications-api
