---

- name: tokens tree
  include_role:
    name: template-filetree
  vars:
    calling_rolename: tokens
    tree_name: tokens

# if using docker, create data dirs
- name: create data dirs 
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tapisdatadir }}/tokens'
  when: tapisflavor == "docker"

