apiVersion: apps/v1
kind: Deployment
metadata:
  name: chords-mysql
spec:
  selector:
    matchLabels:
      app: chords-mysql
  template:
    metadata:
      labels:
        app: chords-mysql
    spec:
      containers:
      - name: chords-mysql
        image: {{ streams_mysql_image }}
        args: ['--ignore-db-dir=lost+found']
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        - name: MYSQL_USER
          value: "chords_demo_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-streams-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          value: "CHORDS_SEEDED_production"
        volumeMounts:
        - name: streams-mysql-data
          mountPath: "/var/lib/mysql"
      volumes:
      - name: streams-mysql-data
        persistentVolumeClaim:
          claimName: {{streams_mysql_pvc}}
