kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{service_param["restheart_mongo_pvc"]}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{universal_param["storage_class"]}}
  resources:
    requests:
      storage: 10Gi


---
apiVersion: batch/v1
kind: Job
metadata:
  name: chown-restheart-mongo-pvc
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: chown-mongo-volume
        image: alpine:latest
        command:
        - chown
        - -R
        - 999:999
        - /data/db
        volumeMounts:
        - name: restheart-mongo-data
          mountPath: /data/db
      volumes:
      - name: restheart-mongo-data
        persistentVolumeClaim:
          claimName: {{service_param["restheart_mongo_pvc"]}}

