networks:
  tapis:
    name: tapis
    external: true

services:
  globus-proxy: 
    restart_policy: unless-stopped
    container_name: globus-proxy
    image: {{ globus_proxy_api_image }}
    networks:
      - tapis
    volumes:
      - ./globus-proxy-config.json:/home/tapis/config.json

