networks:
  tapis:
    name: tapis
    external: true

services:
  globus-proxy: 
    container_name: globus-proxy
    image: {{ globus_proxy_api_image }}
    networks:
      - tapis
    volumes:
      - ./globus-proxy-config.json:/home/tapis/config.json
    ports:
      - 127.0.0.1:5000:5000

