networks:
  tapis:
    name: tapis
    external: true

services:
  globus-proxy: 
    container_name: globus-proxy
    image: {{ globus_proxy_api_image }}
    networks:
      - tapis
    volumes:
      - {{ tapisdir }}/globus-proxy/globus-proxy-config.json:/home/tapis/config.json

