---

networks:
  tapis:
    name: tapis

services:

  tenants-postgres:
    container_name: tenants-postgres
    image: {{ tenants_postgres_image }}
    volumes:
      - {{ tapisdatadir }}/tenants/postgres:/pgdata/data
    networks:
      - tapis
    environment:
      #- POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/pgdata/data
      - POSTGRES_USER=tenants
      - POSTGRES_DB=tenants
      - POSTGRES_PASSWORD

  tenants-migrations:
    container_name: tenants-migrations
    image: {{ tenants_migrations_image }}
    volumes:
      - {{ tapisdir }}/tenants/tenants-config.json:/home/tapis/config.json 
    networks:
      - tapis
    depends_on:
      - tenants-postgres
    environment: 
      - sql_db_url={{ tenants_postgres_url }} 
      - postgres_user=tenants 
      - postgres_database=tenants
      - postgres_password 
      - service_password
      - admin_tenant_public_key
      - dev_tenant_public_key

  tenants-api:
    container_name: tenants-api
    image: {{ tenants_api_image }}
    volumes:
    #   - ./config-local.json:/home/tapis/config.json
    #   - ./service.log:/home/tapis/service.log
      - {{ tapisdir }}/tenants/tenants-config.json:/home/tapis/config.json
      - {{ tapisdir }}/tenants/tenants-service.log:/home/tapis/service.log
    networks:
      - tapis
    environment:
      - sql_db_url={{ tenants_postgres_url }}
      - postgres_user=tenants
      - postgres_database=tenants
      - admin_tenant_public_key
      - dev_tenant_public_key
      - service_password
      - postgres_password
