networks:
  tapis:
    name: tapis
    external: true 

services:
  
  proxy:
    container_name: proxy
    restart_policy: unless-stopped
    image: {{ proxy_nginx_image }}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./locations:/etc/nginx/conf.d/locations:ro
      - {{proxy_nginx_cert_file}}:/tmp/ssl/tls.crt:ro
      - {{proxy_nginx_cert_key}}:/tmp/ssl/tls.key:ro
      - ./token-revoked.json:/etc/nginx/html/token-revoked.json
    networks:
      - tapis
    restart: always
  
  site-router:
    container_name: site-router
    restart_policy: unless-stopped
    image: {{ proxy_site_router_api_image }}
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./site-router-config.json:/home/tapis/config.json:ro
    networks:
      - tapis
    restart: always
  
  site-router-redis:
    container_name: site-router-redis
    restart_policy: unless-stopped
    image: {{ proxy_redis_image }}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - {{ tapisdatadir }}/proxy-site-router-redis:/data
    networks:
      - tapis
    restart: always
