authenticator_api_image: tapis/authenticator:1.3.2
authenticator_migrations_image: tapis/authenticator-migrations:1.3.2
authenticator_postgres_image: postgres:11.4
authenticator_ldap_image: tacc/slapd:1
