kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{actors_mongo_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{actors_storage_class}}
  resources:
    requests:
      storage: 40Gi


---
apiVersion: batch/v1
kind: Job
metadata:
  name: chown-actors-mongo-pvc
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: chown-actors-mongo-volume
        image: {{ actors_alpine_image }}
        command:
        - chown
        - -R
        - 999:999
        - /data/db
        volumeMounts:
        - name: actors-mongo-data
          mountPath: /data/db
      volumes:
      - name: actors-mongo-data
        persistentVolumeClaim:
          claimName: {{actors_mongo_pvc}}

