apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-nfs
spec:
  selector:
    matchLabels:
      app: actors-nfs
  template:
    metadata:
      labels:
        app: actors-nfs
    spec:
      volumes:
      - name: actors-nfs-vol
        persistentVolumeClaim:
          claimName: actors-nfs-vol
      containers:
      - name: actors-nfs
        image: itsthenetwork/nfs-server-alpine:12
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: "/actorsnfs"
        ports:
        - name: actors-nfs
          containerPort: 2049
        volumeMounts:
        - name: actors-nfs-vol
          mountPath: "/actorsnfs"
