
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-nginx
spec:
  selector:
    matchLabels:
      app: actors-nginx
  template:
    metadata:
      labels:
        app: actors-nginx
    spec:
      containers:
      - name: actors-nginx
        image: {{ actors_nginxk8s_image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: actors-nginx-config
          mountPath: /etc/nginx/sites-enabled/flask-project
          subPath: flask-project
      volumes:
      - name: actors-nginx-config
        configMap:
          name: actors-nginx-config
          items:
          - key: flask-project
            path: flask-project

