apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-rabbit
spec:
  selector:
    matchLabels:
      app: actors-rabbit
  template:
    metadata:
      labels:
        app: actors-rabbit
    spec:
      hostname: actors-rabbit # sets static hostname rather than k8 generated. Without rabbit can't use pvc to restart.
      containers:
      - name: actors-rabbit
        image: {{ actors_rabbitmq_image }}
        ports:
        - name: rabbit
          containerPort: 5672
        - name: rabbit2
          containerPort: 15672
        env:
        - name: RABBITMQ_NODENAME
          value: "abaco-rabbit"
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "+A 128"
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: tapis-abaco-secrets
              key: rabbitmq-password
        volumeMounts:
        - name: actors-rabbitmq-data
          mountPath: "/var/lib/rabbitmq"
      volumes:
      - name: actors-rabbitmq-data
        persistentVolumeClaim:
          claimName: {{actors_rabbit_pvc}}
