---
# Grafana Admin
# https://stache.utexas.edu/new/entry/7d98cfa5613484f3680ebad366706a95
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
type: Opaque
data:
  username: {{monitoring_service_grafana_username}}
  password: {{monitoring_service_grafana_password}}