apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps-api
  template:
    metadata:
      labels:
        app: apps-api
    spec:
      containers:
      - name: apps-api
        image: tapis/apps:{{apps_image_version}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8000
            name: "jvm-debug"
        env:
          - name: tapis.db.jdbc.url
            value: jdbc:postgresql://apps-postgres:5432/tapisappdb
          - name: tapis.db.user
            value: tapis_app
          - name: tapis.site.id
            valueFrom:
              configMapKeyRef:
                name: apps-config
                key: site_id
          - name: tapis.tenant.svc.baseurl
            valueFrom:
              configMapKeyRef:
                name: apps-config
                key: service_site_url
          - name: tapis.db.password
            valueFrom:
              secretKeyRef:
                name: tapis-apps-secrets
                key: postgres-password
          - name: tapis.service.password
            valueFrom:
              secretKeyRef:
                name: tapis-apps-secrets
                key: service-password
