apiVersion: v1
kind: Service
metadata:  
  name: jobs-rabbitmq
spec:
  selector:    
    app: jobs-rabbitmq
  ports:  
  - name: jobs-rabbitmq
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:  
  name: jobs-rabbitmq-mgmt
spec:
  type: NodePort
  selector:    
    app: jobs-rabbitmq
  ports:  
  - name: http
    port: 15672
    targetPort: 15672


