---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: files-rabbitmq
  name: {{files_rabbitmq_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{files_storage_class}}
  resources:
    requests:
      storage: 10G