kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{notifications_rabbitmq_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{notifications_storage_class}}
  resources:
    requests:
      storage: 10Gi


