apiVersion: v1
kind: Service
metadata:
  name: notifications-rabbitmq
spec:
  selector:
    app: notifications-rabbitmq
  ports:
  - name: notifications-rabbitmq
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-rabbitmq-mgmt
spec:
  type: NodePort
  selector:
    app: notifications-rabbitmq
  ports:
  - name: http
    port: 15672
    targetPort: 15672
