apiVersion: v1
kind: Service
metadata:  
  name: notifications-rabbitmq
spec:
  selector:    
    app: notifications-rabbitmq
  ports:
  - name: notifications-rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672

