kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{tenants_postgres_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{tenants_storage_class}}
  resources:
    requests:
      storage: 20Gi
