---
# Grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-grafana
  labels:
    app: monitoring-grafana
spec:
  selector:
    matchLabels:
      app: monitoring-grafana
  template:
    metadata:
      labels:
        app: monitoring-grafana
    spec:
      restartPolicy: Always
      initContainers:
      - name: chown-datadir
        image: {{ monitoring_alpine_image }}
        command:
        - chown
        - -R
        - 472:472
        - /var/lib/grafana
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      containers:
      - name: monitoring-grafana
        image: {{ monitoring_grafana_image }}
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-monitoring-secrets
              key:  grafana-password
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SERVER_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: monitoring-config
              key: monitoring_domain
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s/grafana"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-piechart-panel"
        - name: TAPIS_DB_MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-monitoring-secrets
              key: postgres-ro-password
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
          subPath: grafana-datasources.yaml
          #readOnly: false
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: {{monitoring_service_grafana_pvc}}
      - name: grafana-datasources
        configMap:
          name: monitoring-config
