networks:
  tapis:
    name: tapis
    external: true

services:
  vault:
    container_name: vault
    image: {{ vault_image }}
    command: ['vault','server','-config=/vault/config']
    cap_add:
      - IPC_LOCK
    ports:
      - 127.0.0.1:8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl
      - {{ vault_data_dir }}/data:/vault/data
      - {{ vault_data_dir }}/certs:/vault/certs
    networks:
      - tapis
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--proxy", "off", "http://127.0.0.1:8200/v1/sys/health?standbyok=true" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s

