apiVersion: batch/v1
kind: Job
metadata:
  name: systems-e
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: systems-e
        image: {{ systems_postgres_image }}
        imagePullPolicy: Always
        command: ["/tmp/e-sh"]
        volumeMounts:
        - name: systems-init-db-vol
          mountPath: /tmp
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-systems-secrets
              key: postgres-password
      volumes:
      - name: systems-init-db-vol
        configMap:
          name: systems-e
          defaultMode: 0777
  backoffLimit: 4
