apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      {%- if notifications_node_selector | default(None) %}
      nodeSelector:
        exempt: "{{notifications_node_selector}}"
      {%- endif%}
      containers:
      - name: notifications-api
        image: tapis/notifications:{{notifications_image_version}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 8000
            name: "jvm-debug"
        env:
          - name: tapis.db.jdbc.url
            value: jdbc:postgresql://notifications-postgres:5432/tapisntfdb
          - name: tapis.db.user
            value: tapis_ntf
          - name: tapis.site.id
            valueFrom:
              configMapKeyRef:
                name: notifications-config
                key: site_id
          - name: tapis.tenant.svc.baseurl
            valueFrom:
              configMapKeyRef:
                name: notifications-config
                key: service_site_url
          - name: tapis.db.password
            valueFrom:
              secretKeyRef:
                name: tapis-notifications-secrets
                key: postgres-password
          - name: tapis.service.password
            valueFrom:
              secretKeyRef:
                name: tapis-notifications-secrets
                key: service-password
