
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sk-admin-update
spec:
  template:
    spec:
{% if skadmin_sk_privileged_sa is not none %}
      serviceAccountName: {{ skadmin_sk_privileged_sa }}
{% endif %}
      restartPolicy: Never
      containers:
      - name: sk-admin-update
        #command: ["sleep","3600"]
        command: ["/tmp/run-sk-update"]
        image: {{ skadmin_securityadmin_image }} 
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLEID
          valueFrom:
            secretKeyRef:
              name: tapis-sk-vault-secrets
              key: vault-roleid
        - name: VAULT_SECRETID
          valueFrom:
            secretKeyRef:
              name: tapis-sk-vault-secrets
              key: vault-secretid
        #- name: SKADMIN_PARMS
        #  value: "-c -i /tmp/updateLoad -vr VAULT_ROLEID -vs VAULT_SECRETID -b {{skadmin_vault_url}} -kt KUBE_TOKEN -kn KUBE_NAMEPSACE -ku https://kubernetes.default.svc.cluster.local"
        volumeMounts:
        - name: updateload
          mountPath: /tmp/updateLoad
        - name: run-sk-update
          mountPath: /tmp/run-sk-update
          subPath: run-sk-update
      volumes:
      - name: updateload
        configMap:
          name: sk-admin-updateload
      - name: run-sk-update
        configMap:
          name: run-sk-update
          defaultMode: 0777
