apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-rabbitmq
spec:
  selector:
    matchLabels:
      app: jobs-rabbitmq
  template:
    metadata:
      labels:
        app: jobs-rabbitmq
    spec:
      hostname: jobs-rabbitmq
      containers:
      - name: jobs-rabbitmq
        image: rabbitmq:3.8.11-management
        ports:
        - name: rabbitmq
          containerPort: 5672
        - name: http
          containerPort: 15672
        env:
        - name: HOSTNAME
          value: "jobs-rabbitmq"
        - name: RABBITMQ_HOSTNAME
          value: "jobs-rabbitmq"
        - name: RABBITMQ_DEFAULT_USER
          value: "tapis"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets 
              key: rabbitmq-tapis-password
        - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
          value: "2147483648"
        volumeMounts:
        - name: jobs-rabbitmq-data
          mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
      - name: jobs-rabbitmq-data
        persistentVolumeClaim:
          claimName: {{jobs_rabbitmq_pvc}}