apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-health-central
spec:
  selector:
    matchLabels:
      app: pods-health-central
  template:
    metadata:
      labels:
        app: pods-health-central
    spec:
      serviceAccountName: pods-serviceaccount
      containers:
      - name: pods-health-central
        image: {{ pods_api_image }}
        imagePullPolicy: {{pods_image_pull_policy}}
        resources:
          requests:
            cpu: "500m"
            memory: "5M"
          limits:
            cpu: "2"
            memory: "2G"
        env:
        - name: PODS_COMPONENT
          value: health-central
        - name: DEBUG_SLEEP_LOOP
          value: 'false'
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pods-secrets
              key: service-password
        - name: POSTGRES_USERNAME
          value: pods-admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pods-secrets
              key: postgres-password
        - name: RABBITMQ_USERNAME
          value: pods-admin
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pods-secrets
              key: rabbitmq-password
        volumeMounts:
        - name: pods-config
          mountPath: /home/tapis/config.json
          subPath: config.json
        - name: pods-nfs-vol
          mountPath: "/podsnfs"
      volumes:
      - name: pods-config
        configMap: 
          name: pods-config 
      - name: pods-nfs-vol
        nfs:
          server: BURNUP_STATIC_NFS_IP
          path: /