
apiVersion: v1
kind: Service
metadata:
  name: pods-rabbitmq
spec:
  selector:
    app: pods-rabbitmq
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: pods-rabbitmq-dash
spec:
  type: NodePort
  selector:
    app: pods-rabbitmq
  ports:
  - name: rabbitmq-dash
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: pods-postgres
spec:
  type: NodePort
  selector:
    app: pods-postgres
  ports:
  - name: pods-postgres
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: pods-api
spec:
  selector:
    app: pods-api
  ports:
  - name: fastapi
    port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: pods-nginx
spec:
  #type: NodePort
  selector:
    app: pods-nginx
  ports:
  - name: nginx
    port: 80
    targetPort: 80
