---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-elasticsearch
spec:
  selector:
    app: monitoring-elasticsearch
  type: NodePort
  ports:
  - name: el1
    port: 9200
    targetPort: 9200
  - name: el2
    port: 9300
    targetPort: 9300

