
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sk-presetup
spec:
  template:
    spec:
{% if skadmin_sk_privileged_sa is not none %}
      serviceAccountName: {{ skadmin_sk_privileged_sa }}
{% endif %}
      restartPolicy: Never
      containers:
      - name: sk-presetup
        image: {{ skadmin_util_image }}
        command: ["/tmp/create-sk-roles"]
        #command: ["sleep","3600"]
        env:
        - name: VAULT_ADDR
          value: {{skadmin_vault_url}}
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: vault-token
        volumeMounts:
        - name: create-sk-roles
          mountPath: /tmp/create-sk-roles
          subPath: create-sk-roles
        - name: sk-policies
          mountPath: /tmp/sk-policies
        - name: sk-admin-policies
          mountPath: /tmp/sk-admin-policies
        - name: sk-roles
          mountPath: /tmp/sk-roles
      volumes:
      - name: create-sk-roles
        configMap: 
          name: create-sk-roles
          defaultMode: 0777
      - name: sk-policies
        configMap:
          name: sk-policies
      - name: sk-admin-policies
        configMap:
          name: sk-admin-policies
      - name: sk-roles
        configMap:
          name: sk-roles

