apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-rabbitmq
spec:
  selector:
    matchLabels:
      app: notifications-rabbitmq
  template:
    metadata:
      labels:
        app: notifications-rabbitmq
    spec:
      hostname: notifications-rabbitmq
      containers:
      - name: notifications-rabbitmq
        image: {{ notifications_rabbitmq_image }}
        ports:
        - name: rabbitmq
          containerPort: 5672
        - name: http
          containerPort: 15672
        env:
        - name: HOSTNAME
          value: "notifications-rabbitmq"
        - name: RABBITMQ_HOSTNAME
          value: "notifications-rabbitmq"
        - name: RABBITMQ_DEFAULT_USER
          value: "tapis"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: tapis-notifications-secrets 
              key: rabbitmq-password
        - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
          value: "2147483648"
        volumeMounts:
        - name: notifications-rabbitmq-data
          mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
      - name: notifications-rabbitmq-data
        persistentVolumeClaim:
          claimName: {{notifications_rabbitmq_pvc}}
