apiVersion: v1
kind: ConfigMap
metadata:
  name: tokens-config
data:
  tokens-config.json: |-
    {
      "primary_site_admin_tenant_base_url": "{{tokens_service_url}}",
      "service_site_id": "{{tokens_service_site_id}}",
      "service_tenant_id": "{{tokens_service_tenant_id}}",
      "service_name": "{{tokens_service_name}}",
      "log_level": "{{tokens_log_level}}",
      "tenants": {{tokens_tenants|tojson}},
      "show_traceback": {{tokens_show_traceback|tojson}},
      "use_allservices_password": {{tokens_use_allservices_password|tojson}},
      {%- if tokens_use_allservices_password == true %}
      "allservices_password": "{{tokens_allservices_password}}",
      {%- endif %}
      "use_sk": true
    }
