---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: files-api
  name:  files-api
spec:
  replicas: {{local_param["replicas"]}}
  selector:
    matchLabels:
      app: files-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: files-api
    spec:
      {% if local_param["nodeSelector"]%}
      nodeSelector:
        exempt: "{{local_param["nodeSelector"]}}"
      {% endif%}
      containers:
      - name: files-api
        image: tapis/tapis-files:{{local_param["image_version"]|default(service_param["image_version"]|default(universal_param["image_version"]))}}
        {% if local_param["memory"]%}
        resources:
          requests:
            memory: "{{local_param["memory"]}}"
        {% endif%}
        command: ["java"]
        args: {{local_param["args"]|replace("'", "\"")}}
        imagePullPolicy: Always
        ports:
        - name: "files-api"
          containerPort: 8080
        {% if local_param["files-debug"]==true%}
        - name: "files-debug"
          containerPort: 8000
        {% endif %}
        envFrom:
        - configMapRef:
            name: files-environment-vars
        env:
        {% if local_param["node_name"] == true%}
        - name: TAPIS_LOCAL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {% endif%}
        {% if local_param["site_id"] == true%}
        - name: TAPIS_SITE_ID
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: site_id
        {% endif%}
        - name: TOKENS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: service_site_url
        - name: TENANTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: files-config
              key: service_site_url
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets
              key: rabbitmq-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets
              key: postgres-password
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets
              key: service-password
      hostname: files-api
      restartPolicy: Always
