apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-rabbitmq
spec:
  selector:
    matchLabels:
      app: files-rabbitmq
  template:
    metadata:
      labels:
        app: files-rabbitmq
    spec:
      hostname: files-rabbitmq
      containers:
        - name: files-rabbitmq
          image: rabbitmq:3.8.11-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: HOSTNAME
              value: "files-rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: tapis-files-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
              value: "2147483648"
          envFrom:
            - configMapRef:
                name: files-environment-vars
          volumeMounts:
            - name: files-rabbitmq-data
              mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
        - name: files-rabbitmq-data
          persistentVolumeClaim:
            claimName: {{files_rabbitmq_pvc}}
