---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: files-rabbitmq
  name: files-rabbitmq-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{universal_param["storage_class"]}}
  resources:
    requests:
      storage: 10G