apiVersion: v1
kind: Service
metadata:  
  name: sk-api
spec:
  type: NodePort
  selector:    
    app: sk-api
  ports:  
  - name: tomcat2
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:  
  name: sk-api-debug
spec:
  type: NodePort
  selector:    
    app: sk-api
  ports:  
  - name: tomcat1
    port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:  
  name: sk-api-ssl
spec:
  type: NodePort
  selector:    
    app: sk-api
  ports:  
  - name: tomcat3
    port: 8443
    targetPort: 8443

---
apiVersion: v1
kind: Service
metadata:  
  name: sk-api-other
spec:
  type: NodePort
  selector:    
    app: sk-api
  ports:  
  - name: tomcat4
    port: 6157
    targetPort: 6157
