# An example host vars file for a primary site that deploys all 
# Tapis services. This configuration is significantly more complex that the minimal
# primary site, since we have to provide additional configurations for the 
# extra services.
