apiVersion: v1
kind: ConfigMap
metadata: 
  name: files-config
data:
  "service_site_url": "{{files_service_url}}"
  "service_tenant_id": "{{files_service_tenant_id}}"
  "site_id": "{{files_service_site_id}}"
  "service_name": "{{files_service_name}}"
{% if files_globus_client_id is defined %}
  "globus_client_id": "{{files_globus_client_id}}"
{% endif %}

