apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-pgadmin
spec:
  selector:
    matchLabels:
      app: files-pgadmin
  template:
    metadata:
      labels:
        app: files-pgadmin
    spec:
      containers:
      - name: files-pgadmin
        image: {{ files_pgadmin_image }}
        ports:
        - name: http
          containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "wow@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets 
              key: postgres-password
