---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: files
  name: files-rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: files-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: files
  name: files-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: files-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: files
  name: files-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: files-api
