apiVersion: v1
kind: ConfigMap
metadata: 
  name: vault-config
data:
  "service_site_url": "{{ vault_service_url }}"
  "service_tenant_id": "{{ vault_service_tenant_id }}"
  "site_id": "{{ vault_service_site_id }}"
  "service_name": "{{ vault_service_name }}"
