
networks:
    tapis:
        name: tapis
        external: true


services:
    tokens-api:
        container_name: tokens-api
        image: {{ tokens_api_image }}
        volumes:
            - ./tokens-config.json:/home/tapis/config.json
            - ../admin/verification/tokens-test:/home/tapis/healthcheck
        networks:
            - tapis
        env_file: 
            - "{{ tapisdatadir }}/tokens/env"
