
networks:
    tapis:
        name: tapis
        external: true


services:
    tokens-api:
        container_name: tokens-api
        image: {{ tokens_api_image }}
        volumes:
            - '{{ tapisdir }}/tokens/tokens-config.json:/home/tapis/config.json'
            - '{{ tapisdir }}/admin/verification/tokens-test:/home/tapis/healthcheck'
        networks:
            - tapis
        env_file: 
            - "{{ tapisdatadir }}/tokens/env"
        healthcheck: # TODO: fix this
            test: ["CMD-SHELL", "./healthcheck"]
            interval: 5s
            timeout: 5s
            retries: 5
