---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{monitoring_service_prometheus_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{monitoring_service_storage_class}}
  resources:
    requests:
      storage: 20Gi
