apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-registry
spec:
  selector:
    matchLabels:
      app: container-registry
  template:
    metadata:
      labels:
        app: container-registry
    spec:
      containers:
      - name: container-registry
        #command: ['sleep','infinity']
        image: registry:2
        ports:
        - name: registry
          containerPort: 5000
        #volumeMounts:
        #- name: container-registry-config
        #  mountPath: /etc/docker/registry/config.yml
        #  subPath: container-registry-config.yml
      restartPolicy: Always
      #volumes:
      #- name: container-registry-config
      #  configMap:
      #    name: container-registry-config

