
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sk-admin-update
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sk-admin-update
        #command: ["sleep","3600"]
        command: ["/tmp/run-sk-update"]
        image: tapis/securityadmin:{{local_param["image_version"]|default(service_param["image_version"]|default(universal_param["image_version"]|default("dev")))}}
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLEID
          valueFrom:
            secretKeyRef:
              name: tapis-sk-vault-secrets
              key: vault-roleid
        - name: VAULT_SECRETID
          valueFrom:
            secretKeyRef:
              name: tapis-sk-vault-secrets
              key: vault-secretid
        #- name: SKADMIN_PARMS
        #  value: "-c -i /tmp/updateLoad -vr VAULT_ROLEID -vs VAULT_SECRETID -b {{universal_param["vault_url"]}} -kt KUBE_TOKEN -kn KUBE_NAMEPSACE -ku https://kubernetes.default.svc.cluster.local"
        volumeMounts:
        - name: updateload
          mountPath: /tmp/updateLoad
        - name: run-sk-update
          mountPath: /tmp/run-sk-update
          subPath: run-sk-update
      volumes:
      - name: updateload
        configMap:
          name: sk-admin-updateload
      - name: run-sk-update
        configMap:
          name: run-sk-update
          defaultMode: 0777
