apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams-api
spec:
  selector:
    matchLabels:
      app: streams-api
  template:
    metadata:
      labels:
        app: streams-api
    spec:
{% if streams_node_name is not none %}
      nodeName: {{streams_node_name}}
{% endif %}
      containers:
      - name: streams-api
        image: {{ streams_api_image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: tapis_base_url
          valueFrom:
            configMapKeyRef:
              name: streams-config
              key: service_site_url
        - name: chords_api_key
          valueFrom:
            secretKeyRef:
              name: tapis-streams-secrets
              key: chords-api-key
        - name: influxdb_password
          valueFrom:
            secretKeyRef:
              name: tapis-streams-secrets
              key: mysql-password
        - name: alert_secret
          value: testalert
        - name: mysql_password
          valueFrom:
            secretKeyRef:
              name: tapis-streams-secrets
              key: mysql-password
        - name: service_password
          valueFrom:
            secretKeyRef:
              name: tapis-streams-secrets
              key: service-password
        - name: workerCls
          value: "gthread"
{% if streams_processes %}
        - name: processes
          value: "{{streams_processes}}"
{% endif %}
{% if streams_threads %}
        - name: threads
          value: "{{streams_threads}}"
{% endif %}
        volumeMounts:
        - name: streams-config
          mountPath: /home/tapis/config.json
          subPath: streams-config.json
      volumes:
      - name: streams-config
        configMap:
          name: streams-config

