apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflows-pipelines-deployment
  name: workflows-pipelines-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflows-pipelines-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflows-pipelines-deployment
    spec:
      containers:
        - args:
            - python3
            - main.py
          env:
            - name: WORKFLOWS_API_BASE_URL
              value: workflows-api-service
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tapis-workflows-secrets
                  key: rabbitmq-password
            - name: BROKER_PORT
              value: "5672"
            - name: BROKER_URL
              value: workflows-rabbitmq-service
            - name: BROKER_USER
              value: {{workflows_rabbitmq_username}}
            - name: DB_HOST
              value: workflows-mysql-service
            - name: DB_NAME
              value: tasks
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tapis-workflows-secrets
                  key: mysql-password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: {{workflows_mysql_username}}
            - name: DEPLOYMENT_TYPE
              value: {{workflows_pipelines_deployment_type}}
            - name: LOG_LEVEL
              value: {{workflows_log_level}}
            - name: KUBERNETES_NAMESPACE
              value: default
            - name: TAPIS_CONFIG_PATH
              value: "/src/config.json"
            - name: TAPIS_CONFIGSCHEMA_PATH
              value: "/src/configschema.json"
            - name: TAPIS_DEV_URL
              value: {{workflows_tapis_dev_url}}
            - name: TAPIS_SERVICE_SITE_ID
              value: {{workflows_service_site_id}}
            - name: TAPIS_SERVICE_TENANT_ID
              value: {{workflows_service_tenant_id}}
            - name: WORKFLOWS_SERVICE_URL
              value: {{workflows_service_url}}
            - name: WORKFLOWS_SERVICE_ACCOUNT
              value: workflows
            - name: WORKFLOWS_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tapis-workflows-secrets
                  key: service-password
          image: tapis/workflows-pipelines:{{workflows_pipelines_image_tag}}
          imagePullPolicy: Always
          name: workflows-pipelines
          ports:
            - containerPort: 9000
          resources: {}
          tty: true
          volumeMounts:
            - name: pipelines-mount
              mountPath: /mnt/pipelines/
      volumes:
        - name: pipelines-mount
          persistentVolumeClaim:
            claimName: workflows-pipelines-pvc      
      restartPolicy: Always
