
networks:
    tapis:
        name: tapis
        external: true


services:
  monitoring-elisticsearch:
    networks: 
      - tapis

  monitoring-grafana:
    networks: 
      - tapis

  monitoring-kibana:
    networks: 
      - tapis

  monitoring-prometheus:
    networks: 
      - tapis

  monitoring-tapis-exporter:
    networks: 
      - tapis


