{
  service_site_url: {{ monitoring_service_url }}
  monitoring_domain: {{  monitoring_service_url |replace("https://", "") }}
  service_tenant_id: {{ monitoring_service_tenant_id }}
  site_id: {{ monitoring_service_site_id }}
  service_name: {{ monitoring_service_name }}
}