
---
apiVersion: batch/v1
kind: Job
metadata:
  name: renew-sk-secret
spec:
  template:
    spec:
      serviceAccountName: {{ tapis_sk_privileged_sa | default(tapis_privileged_sa) | default('default') }}
      restartPolicy: Never
      containers:
      - name: renew-sk-secret
        command: ["/tmp/renew-sk-secret-script"]
        #command: ["sleep","3600"]
        image: {{ skadmin_skadminutil_image }}
        imagePullPolicy: {{skadmin_image_pull_policy}} 
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: vault-token
        volumeMounts:
        - name: renew-sk-secret
          mountPath: /tmp/renew-sk-secret-script
          subPath: renew-sk-secret-script
      volumes:
      - name: renew-sk-secret
        configMap:
          name: renew-sk-secret
          defaultMode: 0777
