
networks:
    tapis:
        name: tapis
        external: true


services:
  meta-restheart:
    image: {{ meta_rh_server_image }}
    container_name: meta-restheart
    command: [ "java", "-Dfile.encoding=UTF-8", "-server", "-jar", "restheart.jar", "etc/restheart.yml", "--envFile", "etc/config.properties"]
    networks: 
      - tapis
    environment:
      - MONGO_URI=meta-mongo
    volumes:
      - "./meta-config.yml:/opt/restheart/etc/config.properties"
    env_file:
      - {{ tapisdatadir }}/meta/env      

  meta-restheart-security:
    image: {{ meta_api_image }}
    container_name: meta-restheart-security
    environment:
      - TAPIS_SITE_ID={{ meta_service_site_id }}
      - TAPIS_META_SERVICE_TENANT_BASE_URL={{ meta_service_url }}/
      - TAPIS_META_SERVICE_SK_SVC_URL={{ meta_service_url }}/v3
      - TAPIS_META_SERVICE_TOKEN_BASE_URL={{ meta_service_url }}/
      - TAPIS_META_CORE_SERVER=http://restheart:8080/
      - MONGO_URI=meta-mongo
      - CATALINA_OPTS="-Xms16g -Xmx16g -Dlogback.configurationFile=/usr/local/tomcat/etc/logback.xml --add-opens java.base/java.time=ALL-UNNAMED"
    env_file:
      - {{ tapisdatadir }}/meta/env


  meta-mongo:
    image: {{ meta_mongo_singlenode_image }}
    container_name: meta-mongo
    networks: 
      - tapis
    environment:
      - MONGO_INITDB_ROOT_USERNAME="restheart"

    env_file:
      - {{ tapisdatadir }}/meta/env
    # volumes:
    #   -  "{{ meta_restheart_mongo_pvc }}:/data/db"
