
networks:
    tapis:
        name: tapis
        external: true


services:
  restheart:
    image: {{ meta_rh_server_image }}
    container_name: restheart
    command: [ "java", "-Dfile.encoding=UTF-8", "-server", "-jar", "restheart.jar", "etc/restheart.yml", "--envFile", "etc/config.properties"]
    networks: 
      - tapis
    volumes:
      - ./meta-config.yml:/opt/restheart/etc/config.properties
    env_file:
      - {{ tapisdatadir }}/meta/env

  restheart-security:
    image: {{ meta_api_image }}
    container_name: restheart-security
    networks:
      - tapis
    environment:
      - TAPIS_SITE_ID={{ meta_service_site_id }}
      - TAPIS_META_SERVICE_TENANT_BASE_URL={{ meta_service_url }}/
      - TAPIS_META_SERVICE_SK_SVC_URL={{ meta_service_url }}/v3
      - TAPIS_META_SERVICE_TOKEN_BASE_URL={{ meta_service_url }}/
      - TAPIS_META_CORE_SERVER=http://restheart:8080/
      - CATALINA_OPTS=-Dlogback.configurationFile=/usr/local/tomcat/etc/logback.xml --add-opens java.base/java.time=ALL-UNNAMED
    env_file:
      - {{ tapisdatadir }}/meta/env


  restheart-mongo:
    image: {{ meta_mongo_singlenode_image }}
    container_name: restheart-mongo
    networks: 
      - tapis
    environment:
      - MONGO_INITDB_ROOT_USERNAME=restheart
      - MONGO_REPLICA_SET_NAME=rs0
    env_file:
      - {{ tapisdatadir }}/meta/env
    volumes:
      -  {{ tapisdatadir }}/meta/mongodb/data:/data/db
      - ./initdb.sh:/home/tapis/initdb.sh
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" echo init done sleep(5); /home/tapis/initdb.sh ]
    command: >
      bash -c "/usr/bin/mongod --bind_ip_all --replSet rs0 --host restheart-mongo:27017
      && echo init done
      && sleep 5
      && /home/tapis/initdb.sh"
      

    
