kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-backup-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{meta_storage_class}}
  resources:
    requests:
      storage: 10Gi

