apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-nginx
spec:
  selector:
    matchLabels:
      app: pods-nginx
  template:
    metadata:
      labels:
        app: pods-nginx

    spec:
      containers:
      - name: pods-nginx
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: "500M"
          limits:
            cpu: "2"
            memory: "1G"
        ports:
        - name: nginx
          containerPort: 80
        volumeMounts:
        - name: pods-nginx-conf
          mountPath: /etc/nginx/
        - name: pods-certs
          mountPath: /tmp/ssl
        # Reload config every 30 seconds.
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - service nginx reload
          initialDelaySeconds: 30
          periodSeconds: 30

      volumes:
      - name: pods-nginx-conf
        configMap: 
          name: pods-nginx
      - name: pods-certs
        secret:
          secretName: pods-certs
