apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-spawner
spec:
  selector:
    matchLabels:
      app: pods-spawner
  template:
    metadata:
      labels:
        app: pods-spawner
    spec:
      serviceAccountName: pods-serviceaccount
      containers:
      - name: pods-spawner
        image: tapis/pods-api:{{pods_image_version}}
        imagePullPolicy: {{pods_image_pull_policy}}
        command: ["python3", "-u", "/home/tapis/service/spawner.py"]
        resources:
          requests:
            cpu: "500m"
            memory: "5M"
          limits:
            cpu: "2"
            memory: "2G"
        env:
        - name: api
          value: api
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pods-secrets
              key: service-password
        - name: POSTGRES_USERNAME
          value: pods-admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pods-secrets
              key: postgres-password
        - name: RABBITMQ_USERNAME
          value: pods-admin
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pods-secrets
              key: rabbitmq-password
        volumeMounts:
        - name: pods-config
          mountPath: /home/tapis/config.json
          subPath: config.json
      volumes:
      - name: pods-config
        configMap: 
          name: pods-config 

