apiVersion: batch/v1
kind: Job
metadata:
  name: notifications-e
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: notifications-e
        image: bitnami/postgresql:latest
        imagePullPolicy: Always
        command: ["/tmp/e-sh"]
        volumeMounts:
        - name: notifications-init-db-vol
          mountPath: /tmp
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-notifications-secrets
              key: postgres-password
      volumes:
      - name: notifications-init-db-vol
        configMap:
          name: notifications-e
          defaultMode: 0777
  backoffLimit: 4
