apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgrest-api
spec:
  selector:
    matchLabels:
      app: pgrest-api
  template:
    metadata:
      labels:
        app: pgrest-api
    spec:      
      containers:
      - name: pgrest-api
        image: tapis/pgrest-api:{{pgrest_image_version}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: TAPIS_CONFIGSCHEMA_PATH
          value: /home/tapis/configschema.json
        - name: TAPIS_CONFIG_PATH
          value: /home/tapis/config.json
        - name: service_password
          valueFrom:
            secretKeyRef:
              name: tapis-pgrest-secrets
              key: service-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-pgrest-secrets
              key: kubernetes-postgres
        volumeMounts:
        - name: pgrest-config
          mountPath: /home/tapis/config.json
          subPath: pgrest-config.json
      volumes:
      - name: pgrest-config
        configMap: 
          name: pgrest-config
      - name: tapis-pgrest-secrets
        secret:
          secretName: tapis-pgrest-secrets
