apiVersion: v1
kind: ConfigMap
metadata: 
  name: pgrest-config
data:
  pgrest-config.json: |-
    {
      "service_site_url": "{{pgrest_service_url}}",
      "service_tenant_id": "{{pgrest_service_tenant_id}}",
      "site_id": "{{pgrest_service_site_id}}",
      "service_name": "{{pgrest_service_name}}",
      "service_tenant_base_url": "{{upgrest_service_url}}",
      "tenants": {{pgrest_tenants|default(["dev", "admin"])|tojson}},
      "log_level": "DEBUG",
      "show_traceback": false,
      "databases": {
        "default": {
          "NAME": "pgrestdb",
          "USER": "pgrest",
          "PASSWORD": "$env{K8-POSTGRES-PASSWORD}",
          "HOST": "pgrest-postgres",
          "PORT": 5432,
          "ENGINE": "django_tenants.postgresql_backend"
        }
      }
    }

