apiVersion: v1
kind: Service
metadata:  
  name: pgrest-postgres
spec:
  selector:    
    app: pgrest-postgres
  ports:  
  - name: pgrest-postgres
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: pgrest-postgres-nodeport
spec:
  type: NodePort
  selector:
    app: pgrest-postgres
  ports:
  - name: pgrest-postgres
    port: 5432
    targetPort: 5432
