kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{pgrest_postgres_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{pgrest_storage_class}}
  resources:
    requests:
      storage: 20Gi

