kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{proxy_site_router_pvc}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{proxy_storage_class}}
  resources:
    requests:
      storage: 20Gi
