---

- name: get git tag
  command:
    cmd: git tag
  args:
    chdir: "{{ playbook_dir }}"
  register: git_tag

- name: baseburnup tree
  include_role:
    name: template-filetree
  vars:
    calling_rolename: baseburnup
    tree_name: ""

