apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflows-api-deployment
spec:
  selector:
    matchLabels:
      app: workflows-api-deployment
  template:
    metadata:
      labels:
        app: workflows-api-deployment
    spec:
      containers:
      - command: [ "/bin/sh", "-c" ]
        args:
          - "./scripts/start.sh;"
        env:
          - name: BROKER_USER
            value: {{workflows_rabbitmq_username}}
          - name: BROKER_PASSWORD
            valueFrom:
              secretRef:
                name: tapis-workflows-secrets
                key: rabbitmq-password
          - name: BROKER_PORT
            value: "5672"
          - name: BROKER_URL
            value: workflows-rabbitmq-service
          - name: DB_HOST
            value: workflows-mysql-service
          - name: DB_NAME
            value: workflows
          - name: DB_PASSWORD
            valueFrom:
              secretRef:
                name: tapis-workflows-secrets
                key: mysql-password
          - name: DB_USER
            value: {{workflows_mysql_username}}
          - name: DEBUG
            value: 'true'
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretRef:
                name: tapis-workflows-secrets
                key: django-secret-key
          - name: DJANGO_SUPERUSER_EMAIL
            value: {{workflows_django_superuser_email}}
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              secretRef:
                name: tapis-workflows-secrets
                key: django-superuser-password
          - name: DJANGO_SUPERUSER_USERNAME
            value: {{workflows_django_superuser_username}}
          - name: WORKFLOWS_SERVICE_URL
            value: {{workflows_service_url}}
          - name: WORKFLOWS_SERVICE_ACCOUNT
            value: workflows
          - name: WORKFLOWS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tapis-workflows-secrets
                key: service-password
        image: tapis/workflows-api:{{workflows_api_image_tag}}
        imagePullPolicy: Always
        name: workflows-api
        ports:
          - containerPort: 8000
        resources: {}
        tty: true
