---

- name: Generate Tapis Deployment Code
  hosts: tapis_installs

  vars: 
    tapisctl_action: 'generate'

  tasks: 
  - name: Set default values for vars
    include_role: 
      name: get_defaults

  - name: create tapisdir 
    file: 
      path: '{{ tapisdir }}'
      state: directory

  - name: debug remote hosts
    ansible.builtin.debug:
      msg: "{{ groupvars }}"

  - name: set multinode mode
    set_fact:
      multinode: "{{ true if hostvars[groups['remote_hosts']] is defined else false }}"
      cacheable: true

  - name: debug1 is multinode?
    ansible.builtin.debug:
      msg: "is multinode? : {{ multinode }}"

    #check if params are invalid then abort below all tasks.  
  - name: exit
    fail: 
      msg: "exit because of debug"
    when: "param1 is not defined or param2 is not defined"

  - name: set variables for remote components
    include_role: 
      name: multinode
    when: 


### tapis components

  - name: baseburnup role
    include_role:
      name: baseburnup

  - name: generate tapis components
    include_role:
      name: '{{ comp }}'
    loop: '{{ components_to_deploy }}'
    loop_control:
      loop_var: comp


