---

- name: Generate Tapis Deployment Code
  hosts: tapis_installs

  vars: 
    tapisctl_action: 'generate'
  
  tasks: 

  - name: debug
    debug:
      var: tapisflavor 

  - name: Set default values for vars
    include_role: 
      name: get_defaults

  - name: create tapisdir 
    file: 
      path: '{{ tapisdir }}'
      state: directory

### tapis components

  - include_role:
      name: '{{ comp }}'
      apply:
        tags: '{{ comp }}'
    tags:
    - '{{ comp }}'



