---

- name: Generate Tapis Deployment Code
  hosts: all

  vars: 
    tapisctl_action: 'generate'
  
  tasks: 

  - name: create tapisdir 
    file: 
      path: '{{ tapisdir }}'
      state: directory

  - name: create tapisdatadir 
    file: 
      path: '{{ tapisdatadir }}'
      state: directory
    when: tapisdatadir is defined

### tapis components

  - name: baseburnup role
    include_role:
      name: baseburnup

  - name: generate tapis components
    include_role:
      name: '{{ comp }}'
    loop: '{{ components_to_deploy }}'
    loop_control:
      loop_var: comp


