---

- name: Generate Tapis Deployment Code
  hosts: all

  vars: 
    tapisctl_action: 'generate'
  
  tasks: 

  - name: create tapisdir 
    file: 
      path: '{{ tapisdir }}'
      state: directory

### tapis components

  - include_role:
      name: '{{ comp }}'
      apply:
        tags: '{{ comp }}'
    tags:
    - '{{ comp }}'



