---
# This is a helper playbook to copy the burnups for components you'd like to place on a different host than the main deployer host

# This playbook should be run ONLY on remote_hosts, a separate group in your Ansible inventory.

# This playbook assumes it is running on the "main" deployment host, AFTER burnup has been run (to populate skadmin/env file.

- name: Map Tapis components to hosts
  hosts: remote_hosts
  vars:
    tapis_remote_dir: "{{ hostvars[groups['tapis_installs'][0]]['tapisdir'] }}"
    tapis_remote_data_dir: "{{ hostvars[groups['tapis_installs'][0]]['tapisdatadir'] }}"
  tasks:
  
    - name: Set location variables for each host
      ansible.builtin.set_fact: 
        "{{ item }}_host": "{{ inventory_hostname }}"
        cacheable: True
      loop: "{{ components_to_deploy }}"

    - name: debug5 print location facts
      ansible.builtin.debug:
        msg: "{{ item + '_host' }} :: {{ lookup('ansible.builtin.vars', item + '_host') }}"
      loop: "{{ components_to_deploy }}"
