---

- name: test playbook for experimenting
  hosts: all

  vars:
    tapisctl_action: example-docker
  
  tasks: 

  - name: 
    fail: 
      msg: Required var 'tapisctl_action' is not defined.
    when: tapisctl_action is not defined

  - include_role: 
      name: example-role





