---
apiVersion: v1
kind: Service
metadata:  
  name: restheart
spec:
  selector:    
    app: restheart
  ports:  
  - name: restheart
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:  
  name: restheart-debug
spec:
  type: NodePort
  selector:    
    app: restheart
  ports:  
  - name: restheart-debug
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:  
  name: restheart-security
spec:
  type: NodePort
  selector:    
    app: restheart-security
  ports:  
  - name: restheart-security
    port: 8080
    targetPort: 8080



