
networks:
    tapis:
        name: tapis

services:
  authenticator-api: 
    image: {{ authenticator_api_image }}
    # ports:
    #     - "127.0.0.1:5000:5000"
    networks:
        - tapis
    environment: # TODO
        dev_ldap_bind_credential: "dev-ldap-bind-credential"
        postgres_password: "postgres-password"
        service_password: "service-password"
    volumes:
        - "{{ tapisdir }}/authenticator/authenticator-config.json:/home/tapis/config.json"
        # - "{{ tapisdatadir }}/authenticator/api/service.log:/home/tapis/service.log"
    container_name: authenticator-api
    depends_on: 
        - authenticator-postgres


  authenticator-postgres:
    image: {{ authenticator_postgres_image }}
    # ports:
    #     - "127.0.0.1:5432:5432"
    networks:
        - tapis
    environment:
        PGDATA: "/pgdata/data"
        POSTGRES_USER: "authenticator"
        POSTGRES_DB: "authenticator"
        POSTGRES_PASSWORD: "postgres-password" # TODO
    volumes:
        - {{ tapisdatadir }}/authenticator/postgres:/data/pgdata
    container_name: authenticator-postgres
        
  authenticator-ldap:
    image: {{ authenticator_ldap_image }}
    # ports:
    #     - "127.0.0.1:389:389"
    networks:
        - tapis
    environment: #TODO
        LDAP_DOMAIN: "LDAP_DOMAIN"
        LDAP_ORGANISATION: "LDAP_ORGANISATION"
        LDAP_ROOTPASS: "dev-ldap-bind-credential"
    volumes:
        - {{ tapisdatadir }}/authenticator/ldap:/data/ldap
    container_name: authenticator-ldap

networks:
    tapis:
