networks:
    tapis:
        name: tapis
        external: true

services:
  authenticator-api: 
    restart_policy: unless-stopped
    container_name: authenticator-api
    image: {{ authenticator_api_image }}
    networks:
        - tapis
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    volumes:
        - ./authenticator-config.json:/home/tapis/config.json
    depends_on: 
        authenticator-postgres:
            condition: service_healthy
        authenticator-ldap:
            condition: service_started
        authenticator-migrations:
            condition: service_completed_successfully


  authenticator-postgres:
    container_name: authenticator-postgres
    image: {{ authenticator_postgres_image }}
    networks:
        - tapis
    environment:
        - PGDATA=/pgdata/data
        - POSTGRES_USER=authenticator
        - POSTGRES_DB=authenticator
        - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    volumes:
        - {{ tapisdatadir }}/authenticator/postgres:/pgdata
    healthcheck:
        test: pg_isready -U authenticator


  authenticator-migrations:
    container_name: authenticator-migrations
    image: {{ authenticator_migrations_image }}
    networks:
        - tapis
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    depends_on:
        authenticator-postgres:
            condition: service_healthy
        authenticator-ldap:
            condition: service_started
    command: ['upgrade']
    volumes:
        - ./authenticator-config.json:/home/tapis/config.json
        
        
  authenticator-ldap:
    container_name: authenticator-ldap
    image: {{ authenticator_ldap_image }}
    networks:
        - tapis
    environment:
        - LDAP_DOMAIN=tapis
        - LDAP_ORGANISATION=Tapis
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    volumes:
        - {{ tapisdatadir }}/authenticator/ldap:/data/ldap
    depends_on:
        authenticator-postgres:
            condition: service_healthy
    healthcheck:
        test: slapcat

