networks:
    tapis:
        name: tapis
        external: true

services:
  authenticator-api: 
    container_name: authenticator-api
    image: {{ authenticator_api_image }}
    networks:
        - tapis
    environment:
        - dev_ldap_bind_credential # this seems to be missing from skexport, maybe it's created when authenticator-ldap is spun up?
        - postgres_password
        - service_password
    volumes:
        - "{{ tapisdir }}/authenticator/authenticator-config.json:/home/tapis/config.json"
        # - "{{ tapisdatadir }}/authenticator/api/service.log:/home/tapis/service.log"
    depends_on: 
        - authenticator-postgres


  authenticator-postgres:
    container_name: authenticator-postgres
    image: {{ authenticator_postgres_image }}
    networks:
        - tapis
    environment:
        - PGDATA=/pgdata/data
        - POSTGRES_USER=authenticator
        - POSTGRES_DB=authenticator
        - POSTGRES_PASSWORD
    volumes:
        - {{ tapisdatadir }}/authenticator/postgres:/data/pgdata

    #  authenticator-migrations:
    #container_name: authenticator-migrations
    #image: {{ authenticator_migrations_image }}
    #networks:
    #    - tapis
    
        
  authenticator-ldap:
    container_name: authenticator-ldap
    image: {{ authenticator_ldap_image }}
    networks:
        - tapis
    environment:
        - LDAP_DOMAIN="tapis"
        - LDAP_ORGANISATION="tapis"
        - LDAP_ROOTPASS
    volumes:
        - {{ tapisdatadir }}/authenticator/ldap:/data/ldap
