networks:
    tapis:
        name: tapis
        external: true

services:
  authenticator-api: 
    container_name: authenticator-api
    image: {{ authenticator_api_image }}
    networks:
        - tapis
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    volumes:
        - "{{ tapisdir }}/authenticator/authenticator-config.json:/home/tapis/config.json"
    depends_on: 
        - authenticator-postgres
        - authenticator-ldap
        - authenticator-migrations


  authenticator-postgres:
    container_name: authenticator-postgres
    image: {{ authenticator_postgres_image }}
    networks:
        - tapis
    environment:
        - PGDATA=/pgdata/data
        - POSTGRES_USER=authenticator
        - POSTGRES_DB=authenticator
        - POSTGRES_HOST_AUTH_METHOD=trust
        # - POSTGRES_PASSWORD
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    volumes:
        - {{ tapisdatadir }}/authenticator/postgres:/var/lib/postgresql/data


  authenticator-migrations:
    container_name: authenticator-migrations
    image: {{ authenticator_migrations_image }}
    networks:
        - tapis
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    depends_on:
        - authenticator-postgres
        - authenticator-ldap
    command: ['upgrade']
    volumes:
        - "{{ tapisdir }}/authenticator/authenticator-config.json:/home/tapis/config.json"
        
        
  authenticator-ldap:
    container_name: authenticator-ldap
    image: {{ authenticator_ldap_image }}
    networks:
        - tapis
    environment:
        - LDAP_DOMAIN=tapis
        - LDAP_ORGANISATION=Tapis
    env_file:
        - {{ tapisdatadir }}/authenticator/env
    volumes:
        - {{ tapisdatadir }}/authenticator/ldap:/data/ldap
        - "{{ tapisdir }}/authenticator/authenticator-config.json:/home/tapis/config.json"
    depends_on:
        - authenticator-postgres

