---
apiVersion: v1
kind: Service
metadata:
  name: tapis-nginx
spec:
  type: NodePort
  selector:
    app: tapis-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: http2
    port: 443
    targetPort: 443

