apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-pbm
spec:
  selector:
    matchLabels:
      app: meta-pbm
  template:
    metadata:
      labels:
        app: meta-pbm
    spec:
      containers:
        - name: meta-pbm
          image: {{ meta_mongodb_backup_image }}
          imagePullPolicy: Always
          env:
            - name: PBM_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: restheart-security-mongo-uri
                  key: restheart-security-mongo-uri
          volumeMounts:
            - name: config
              mountPath: /pbm_config.yml
              subPath: pbm_config.yml
      volumes:
        - name: config
          configMap:
            name: pbm-config

