name: Docker Image CI

on:
  push:
    branches: [ test,dev ]
  pull_request:
    branches: [ test,dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tapis/deployer-input-gen:${{ steps.extract_branch.outputs.branch }}

    - name: Push the image to dockerhub
      run: docker push tapis/deployer-input-gen:${{ steps.extract_branch.outputs.branch }}
