apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-rdr-recovery
spec:
  selector:
    matchLabels:
      app: jobrdr
  template:
    metadata:
      labels:
        app: jobrdr
    spec:
      initContainers:
      automountServiceAccountToken: false
      {% if jobs_node_selector is defined %}
        {% if jobs_node_selector == true %}
      nodeSelector:
        exempt: "yes"
        {% endif %}
      {% endif %}
      containers:
      - name: jobs-rdr-recovery
        image: tapis/jobsworker:{{jobs_image_version}}
        imagePullPolicy: Always
        env:
        {% if jobs_node_name == true%}
        - name: tapis.local.node.name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {% endif%}
        - name: tapis.site.id
          valueFrom:
            configMapKeyRef:
              name: jobs-config
              key: site_id
        - name: tapis.tenant.svc.baseurl
          valueFrom:
            configMapKeyRef:
              name: jobs-config
              key: service_site_url
        - name: tapis.service.password
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: service-password
        - name: tapis.db.connection.pool.size
          value: "5"
        - name: tapis.db.user
          value: "tapis"
        - name: tapis.db.password
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: tapis-postgres-password
        - name: tapis.db.jdbc.url
          value: "jdbc:postgresql://jobs-postgres:5432/tapisjobsdb"
        - name: tapis.queue.host
          value: jobs-rabbitmq
        - name: tapis.queue.admin.user
          value: "tapis"
        - name: tapis.queue.admin.password
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: rabbitmq-tapis-password
        - name: tapis.queue.user
          value: "jobs"
        - name: tapis.queue.password
          valueFrom:
            secretKeyRef:
              name: tapis-jobs-secrets
              key: rabbitmq-jobs-password
        - name: tapis.request.logging.filter.prefixes
          value: "/v3/jobs"
        - name: JAVA_OPTS 
          value: "-Xms1g -Xmx3g"
        - name: MAIN_CLASS
          value: "edu.utexas.tacc.tapis.jobs.reader.RecoveryReader"
        - name: JOBS_PARMS
          value: "-n rdr-recovery"
