apiVersion: apps/v1
kind: Deployment
metadata:
  name: chords-influxdb2
spec:
  selector:
    matchLabels:
      app: chords-influxdb2
  template:
    metadata:
      labels:
        app: chords-influxdb2
    spec:
      containers:
      - name: chords-influxdb2
        image: {{ streams_influxdb2_image }}
        ports:
        - name: influx1
          containerPort: 8086
        - name: influx2
          containerPort: 8083
        env:
        - name: INFLUXDB_HTTP_MAX_ROW_LIMIT
          value: "1000000"
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "streams"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "myawesometapistoken"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "tapis"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "admin"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-streams-secrets
              key: mysql-password
        volumeMounts:
        - name: influx-data
          mountPath: "/var/lib/influxdb2"
      volumes:
      - name: influx-data
        persistentVolumeClaim:
          claimName: {{streams_influx2_pvc}}

